# Generated by Django 5.2.4 on 2025-07-27 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.TextField()),
                ('classified_as', models.CharField(choices=[('ham', 'Ham'), ('spam', 'Spam')], max_length=10)),
                ('prediction_confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_feedback_provided', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='Was the classification correct?')),
                ('user_comment', models.TextField(blank=True, help_text='Optional comments from the user.', null=True)),
                ('feedback_timestamp', models.DateTimeField(auto_now_add=True)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.emailclassification')),
            ],
            options={
                'verbose_name_plural': 'Classification Feedback',
            },
        ),
    ]
